# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
   encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

   role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

   providers:
        fos_userbundle:
            id: fos_user.user_provider.username

   firewalls:
        main:
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /profile
            anonymous: true
            oauth:
                resource_owners:
                    google: "/login/check-google"
                    facebook: "/login/check-facebook"
                    twitter: "/login/check-twitter"
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    #service: hwi_oauth.user.provider.fosub_bridge
                    service: symfonyzero.provider.oauth
            logout:       true
            anonymous:    true
            switch_user:  true

   access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
