parameters:
    symfonyzero.user.repository.class: AppBundle\Repository\UserRepository

services:
    symfonyzero.user.repository:
        class: "%symfonyzero.user.repository.class%"
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ AppBundle\Entity\User ]